### PR TITLE
Save functionality added in GUI file menu

### PR DESCRIPTION
**Pull request by realsdx**
#81 Added the save functionality in GUI filemenu

### CODE REVIEW

**Comment by djmgit** [comment]
saveerror

Please have a look at this.

**Comment by realsdx** [comment]
ok.. i will look into it

**Comment by djmgit** [comment]
@realsdx great :)

**Comment by realsdx** [comment]
its for python3 only
in python2 its tkFileDialog... should i add support for python2 ???

**Comment by djmgit** [comment]
@realsdx yes please, actually as of now the app is for both py2 and py3. So py2 support is required :)

**Comment by realsdx** [comment]
Done.

**Comment by djmgit** [comment]
@realsdx will review it ASAP

**Comment by realsdx** [comment]
I forgot squash the commits, sorry for that

**Comment by djmgit** [comment]
@realsdx since this is your second PR, it is a good time to learn how to squash commits. I would suggest you to squash your commits for this PR as it is very essential :)

**Pull request merged**
