### PR TITLE
Fix issue #32 -implemented dark/light theme

### PR DESCRIPTION
**Pull request by LoneOne123**
so ive implemeted dark/light theme + a button to switch them
plus new option to use light/dark theme from terminal with -t
here the 2 themes as image
darktheme
lighttheme

was a bit code i hope i got everything

### CODE REVIEW

**Comment by djmgit** [comment]
tkinter1

The dark theme is not applied properly when the app is launched for the first time. The color of the root's background and some labels are not in agreement with those of the dark theme.

@Aniq55 Should we keep dark theme when the app starts for the first time or light theme?

**Comment by LoneOne123** [comment]
On my system it's fine, can u upload a Screenshot? Then i can correct it

**Comment by LoneOne123** [comment]
So ok should be fixed try it again ;)

**Comment by Aniq55** [comment]
@LoneOne123 I think the light theme should be default. Just like other apps.

**Comment by djmgit** [comment]
@LoneOne123 The bug is solved.
@Aniq55 I too feel that light theme should be default. @LoneOne123 Please can you make light theme to be the default one.

**Comment by LoneOne123** [comment]
I will when i get up today ;)

**Comment by LoneOne123** [comment]
so @Aniq55 @djmgit now u can have a look again changed the default theme to light ;)

**Comment by Aniq55** [comment]
Great work @LoneOne123

**Pull request merged**
