### PR TITLE
Dotplot : Added functionality to plot multiple dots,Fixed some errors in plot_line function

### PR DESCRIPTION
**Pull request by realsdx**
#17  Added functionality to plot multiple dots (even single) on a figure.
#85  Fixed all the issues mentioned here except Documentation

### CODE REVIEW

**Comment by djmgit** [comment]
@realsdx Nice work, just a few suggestions which you can follow from next time.
Please do not club issues together while creating PRs. If necessary create multiple PRs :) In this way length of PRs will remain small and also it is easier to review and track.

Welcome On board.

**Comment by realsdx** [comment]
Deleted test.py

**Comment by realsdx** [comment]
Thanks for the suggestion.

**Comment by realsdx** [comment]
No.. that time I don't know that I can't remove a file from remote using gitignore

**Comment by djmgit** [comment]
@realsdx Congrats, your first PR has been merged.

From next time, when you make multiple commits, please squash them into a single one before making PR :) It keeps things more organised :)

**Pull request merged**
